# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4832256460be0db21f5756f05b415abed994ed5b7b063dcd5a32920befbcb98a62553a4591863791ab9b1b3151b93917ed8a74feff417df7692e88d80f96827

test:
  secret_key_base: 529980f977ac9bbc87144e5059c4ee5ee19cfe33c0d79d7c489ee307fa61be3708ef203800403221b7367a66ff18f976ad9d4665c3ee3a555ab8da0c44bb9d98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
